language: bash

os: 
  - windows
  - linux
  - osx

env:
  - TEST_SUITE=test1

before_install:
  # install conda
  - wget https://raw.githubusercontent.com/trichter/conda4travis/latest/conda4travis.sh -O conda4travis.sh
  - source conda4travis.sh
  
  # install conda environment
  - conda env create -f ./environment.yaml
  - conda activate pypsa-eur
  
  # install open-source solver
  - conda install -c conda-forge ipopt glpk

script:
  - cp ./test/config.$TEST_SUITE.yaml ./config.yaml
  - snakemake -j 2 solve_all_elec_networks
